name: Self-Hosted Counter Deployment
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  package:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Build debian package
        run: |
          make build-deb
  copy:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: package
    steps:
      - uses: actions/checkout@v4
      - name: copy package via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "counter-v2.0.0.deb"
          target: "/tmp/"
  install:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: copy
    steps:
      - uses: actions/checkout@v4
      - name: Install debian package
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y dpkg
            sudo dpkg -i /tmp/counter-v2.0.0.deb
