name: Self-Hosted Counter Deployment
on:
  workflow_run:
    workflows: ["Self-Hosted Counter Integration"]
    types:
      - completed
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  # push:
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Install run tools
        run: |
          apt-get update -q && apt-get install -y make
      - name: Run binary
        run: |
          make run &
          ps aux | grep counter