name: Self-Hosted Counter Integration
on: [push]
jobs:
  test:
    runs-on: [self-hosted, linux, x64, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Install test tools
        run: |
          apt-get update && apt-get install -y make golang
      - name: Run tests
        run: |
          make test
  build:
    runs-on: [self-hosted, linux, x64, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 2
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: |
          apt-get update && apt-get install -y make golang
      - name: Build binary
        run: |
          make build
