name: Self-Hosted Counter Integration
on: [push]
jobs:
  test:
    runs-on: [self-hosted, linux, x64, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Install make
        run: |
          apt-get update -q && apt-get install -y make
      - name: Run tests
        run: |
          make test
  build:
    runs-on: [self-hosted, linux, x64, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 5
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Install make
        run: |
          apt-get update -q && apt-get install -y make
      - name: Build binary
        run: |
          make build
  package:
    runs-on: [self-hosted, linux, x64, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 5
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Install make
        run: |
          apt-get update -q && apt-get install -y make
      - name: Build debian package
        run: |
          make build-deb
      - name: Store debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: counter-v2.0.0
          path: |
            counter-v2.0.0.deb
  lint:
    runs-on: [self-hosted, linux, x64, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 5
    needs: package
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Install linting tools
        run: |
          apt-get update -q && apt-get install -y make lintian
      - name: Lint debian package
        run: |
          make lint-deb
