name: Self-Hosted Counter BTPL
on: [push]
jobs:
  dependencies:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Print working directory
        run: |
          pwd
  test:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Print working directory
        run: |
          pwd
      - name: Run tests
        run: |
          make test
  build:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Print working directory
        run: |
          pwd
      - name: Build binary
        run: |
          make build
  package:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build debian package
        run: |
          make build-deb
      - name: Store debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: counter-v2.0.0
          path: |
            counter-v2.0.0.deb
  lint:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: package
    steps:
      - uses: actions/checkout@v4
      - name: Install lintian
        run: |
          sudo apt-get install -y lintian
      - name: Lint debian package
        run: |
          make lint-deb
