name: Systemd Counter Debian Packaging
on: [push]
jobs:
  dependencies:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential
  setup-go:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    strategy:
      matrix:
        go-version: [1.22.0]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
  build:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: [dependencies, setup-go]
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        run: |
          make build
  test:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          make test
  package:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build debian package
        run: |
          make build-deb
      - name: Store debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: counter-v2.0.0
          path: |
            counter-v2.0.0.deb
  lint:
    runs-on: [self-hosted, linux, x64, CPSC334]
    timeout-minutes: 2
    needs: package
    steps:
      - uses: actions/checkout@v4
      - name: Install lintian
        run: |
          sudo apt-get install -y lintian
      - name: Lint debian package
        run: |
          make lint-deb
