name: Self-Hosted Counter Deployment
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Install test tools
        run: |
          apt-get update && apt-get install -y make wget
      - name: Install golang
        run: |
          make golang-install
          export PATH=$PATH:/usr/local/go/bin
      - name: Install go dependencies
        run: |
          go mod download
      - name: Build binary
        run: |
          make build
      - name: Copy binary to gcp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "bin/counter"
          target: /tmp/
      - name: Run binary on gcp
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            /tmp/counter
